/**
 * Service worker generation.
 *
 * Quartz needs to work with no network at all, so the shell and the bundled
 * timetable data are precached at install time. A hand-written worker is used
 * instead of a toolkit because the caching rules are small, and being able to
 * read exactly what is cached — and when an update is allowed to take effect —
 * matters more here than generality.
 */

import { readdirSync, statSync } from 'node:fs';
import { join, posix, relative, sep } from 'node:path';
import type { Plugin } from 'vite';

const listFiles = (dir: string): string[] => {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries.flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? listFiles(full) : [full];
  });
};

const renderWorker = (cacheName: string, base: string, precache: readonly string[]): string => `/*
 * Generated by plugins/serviceWorker.ts. Do not edit.
 */
const CACHE = ${JSON.stringify(cacheName)};
const BASE = ${JSON.stringify(base)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const SHELL = BASE + 'index.html';

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

/*
 * The new worker deliberately does not claim open pages. A day in progress is
 * never reloaded underneath the user; an update takes effect at the next launch.
 */
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      ),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Any in-app route resolves to the cached shell, so a refresh or a direct
  // link works offline and without server rewrite rules.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches
        .match(SHELL)
        .then((cached) => cached || caches.match(BASE))
        .then((cached) => cached || fetch(request)),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`;

export const quartzServiceWorker = (publicDir = 'public'): Plugin => {
  let base = '/';

  return {
    name: 'quartz-service-worker',
    apply: 'build',
    configResolved(config) {
      base = config.base;
    },
    generateBundle(_options, bundle) {
      const fromBundle = Object.keys(bundle).filter((name) =>
        /\.(js|css|html|json|webmanifest|svg|png|ico|woff2?)$/.test(name),
      );
      const fromPublic = listFiles(publicDir).map((file) =>
        relative(publicDir, file).split(sep).join(posix.sep),
      );

      const precache = [
        ...new Set([
          // The shell is emitted after this hook runs, and offline navigation
          // asks for the directory path rather than the file name, so both are
          // listed explicitly.
          base,
          `${base}index.html`,
          ...[...new Set([...fromBundle, ...fromPublic])].map((name) => `${base}${name}`).sort(),
        ]),
      ];

      // Any change to the precache list invalidates the cache, so a deploy can
      // never leave a half-updated mixture of old and new assets.
      const hash = precache
        .join('|')
        .split('')
        .reduce((acc, char) => (acc * 31 + char.charCodeAt(0)) >>> 0, 7);

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: renderWorker(`quartz-${hash.toString(36)}`, base, precache),
      });
    },
  };
};
